import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/Provider/ThemeProvider';
import { Toaster } from "@/components/ui/sonner"
import Navbar from '@/components/Navbar';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={'eng'} suppressHydrationWarning>
      <body
        dir="ltr"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="flex flex-col justify-between min-h-screen relative">
            <Navbar />
            <div className="px-20 mt-28">{children}</div>
            {/* <div className="my-10 mx-auto flex justify-center">{ads} </div> */}
            <footer className="bg-black w-full h-10 text-white flex items-center justify-center">
              <p>Footer</p>
            </footer>
          </main>
             <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
